# Generated by Django 2.1 on 2018-08-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('S', 'Start'), ('E', 'End')], max_length=1)),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.IntegerField()),
                ('source', models.CharField(max_length=11)),
                ('destination', models.CharField(max_length=11)),
            ],
        ),
    ]
